// <auto-generated />
using BankPortalMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankPortalMVC.Migrations
{
    [DbContext(typeof(ResponseDBContext))]
    [Migration("20200928080634_R")]
    partial class R
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankPortalMVC.Models.ViewAccountCustRes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AccBal")
                        .HasColumnType("float");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("AccType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("viewAccountCustRes");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewAccountDetailsResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AccBal")
                        .HasColumnType("float");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("AccType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("viewAccountDetailsResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewAccountStatementResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("closingBalance")
                        .HasColumnType("float");

                    b.Property<int>("date")
                        .HasColumnType("int");

                    b.Property<double>("deposit")
                        .HasColumnType("float");

                    b.Property<int>("refno")
                        .HasColumnType("int");

                    b.Property<int>("valueDate")
                        .HasColumnType("int");

                    b.Property<double>("withdrawal")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("viewAccountStatementResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewCurrentServiceResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AccBal")
                        .HasColumnType("float");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("viewCurrentServiceResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewDepositResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AccBal")
                        .HasColumnType("float");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("DepositStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("viewDepositResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewNewCustomerResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentAccountId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavingsAccountId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("viewNewCustomerResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewSavingsServiceResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AccBal")
                        .HasColumnType("float");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("viewSavingsServiceResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewTransferResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("rbal")
                        .HasColumnType("float");

                    b.Property<double>("sbal")
                        .HasColumnType("float");

                    b.Property<string>("transferStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("viewTransferResponses");
                });

            modelBuilder.Entity("BankPortalMVC.Models.ViewWithdrawResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AccBal")
                        .HasColumnType("float");

                    b.Property<int>("AccId")
                        .HasColumnType("int");

                    b.Property<string>("WithdrawStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("viewWithdrawResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
